### ISSUE TITLE
time axis is mangled in some data sets

### ISSUE THREAD

**Issue by jhidding** [abrupt-climate/hypercc#4]
the time axis sometimes gets messed up in the signal plot from hypercc, for example in mrso, CCSM4. It seems to pick the time period from only one file, not all files, and then the events are shown for the whole time period, but the horizontal axis for the signal is only shown for part of the time, making the events occur at the wrong time in the figure.

**Comment by jhidding** [comment]
Do the files in the same dataset all use different starting dates  for their time units?

**Comment by bathiany** [comment]
That was indeed the problem.
This case is rare in CMIP5 data => issue closed for now.
